JasonGross/coq-tools

- .gitignore
- examples/Makefile
- examples/example_26/example_26/example_26.v
- examples/example_26/foo/bar/A.v
- examples/run-example-26.sh
- replace_imports.py
Waiting to make sure the test-suite runs on other versions of Coq
> Allow the minimizer to work when only -Q is passed

- diagnose_error.py
- examples/run-example-00.sh
- examples/run-example-12.sh
- examples/run-example-13.sh
- examples/run-example-15.sh
- examples/run-example-25.sh
- examples/run-example-26.sh
- find-bug.py
The old behavior can be restored with --strict-whitespace
Fixes #46
> By default, don't be so strict about whitespace

- find-bug.py
Fixes #45, even in --strict-whitespace mode
> Remove more instances of the Admit module

- examples/example_25/example_25.v
- examples/example_48/example_48.v
- examples/run-example-25.sh
- examples/run-example-48.sh
- find-bug.py
Fixes #79
I expect that admitting definitions does not take that much time (I
believe most of the time is spent trying to remove each line one at a
time), so we just try both.
> Prefer `Admitted` rather than `admit. Defined`

- .github/workflows/ci.yml
- Makefile
- examples/example_24/expected/run.log
- import_util.py
- minimize-requires.py
- replace_imports.py
This changes the numbers in get_require_locations by 1, but I think that function was previously unused.
> Factor some use of glob files

- examples/run-example-42.sh
- find-bug.py
- import_util.py
- minimize-requires.py
This will probably handle 99% of #78.  What remains is a pass to move `Require` up as high as possible.
On top of #84
> Add a pass that splits `Require`

- .github/workflows/ci-dev.yml
- coqtop-as-coqc.sh
- examples/Makefile
- examples/example_08/A.v
- examples/example_09/A.v
- examples/example_18/example_18.v
- examples/run-example-00.sh
- examples/run-example-08.py
- examples/run-example-28.sh
- examples/run-example-29.sh
- examples/run-example-31.sh
- examples/run-example-35.sh
- examples/run-example-36.sh
- examples/run-example-38.sh
- examples/run-example-39.sh
- examples/run-example-42.sh
- examples/run-example-45.sh
- import_util.py
Version of #96 where we only use docker for 8.4, since there seems to be some native compiler issue with newer versions
> Test 8.4 again

- find-bug.py
- util.py
Makes it a bit easier to see what is happening.
> add color for success/nothing changed messages

- import_util.py
Should deal with the bug exposed by https://github.com/coq/coq/pull/15880
> Pass `KEEP_ERROR=1` unless coq_makefile is old

- .github/workflows/ci-dev.yml
> Use default ocaml version in ci-dev

- coq_version.py
- find-bug.py
- split_definitions.py
Should deal with https://github.com/coq/coq/pull/16190#issuecomment-1164689959
> Split statements to definitions with passing coqc

- .github/workflows/ci-check.yml
- .github/workflows/ci-dev-check.yml
- .github/workflows/ci-dev.yml
- .github/workflows/ci.yml
Works around https://github.com/orgs/community/discussions/28864
> Use a different method to check for CI success

- coq_version.py
- examples/Makefile
- examples/example_057/example_057.v
- examples/run-example-057.sh
> Fix splitting of help string

- find-bug.py
- import_util.py
- inline-imports.py
> Don't use coq_makefile when --no-deps is passed

- coq_tools/import_util.py
There should be no semantic change
> Add parentheses for clarity

- .github/workflows/publish.yml
- .github/workflows/standalone.yml
Maybe we need them both at once?
Closes #186
Closes #188
> Bump actions/download-artifact and actions/upload-artifact from 3 to 4

- examples/run-example-008.py
- examples/run-example-032.sh
- examples/run-example-033.sh
Add more complicated handling for Coq => Stdlib of coq/coq#19310.
> Partial compat with coq/coq#19310

- coq_tools/find_bug.py
Minor addition for coq/coq#19310
> Add `--inline-stdlib` alias of `--inline-coqlib`

- coq_tools/import_util.py
Compatibility with coq/coq#19310
> Account for Coq => Stdlib replacement

- coq_tools/find_bug.py
- coq_tools/import_util.py
- examples/Makefile
- examples/example_063/example_063.v
- examples/run-example-063.sh
> Thread `-top` from failing coqc

- coq_tools/find_bug.py
> Thread through base_dir in more places

- coq_tools/import_util.py
cf https://github.com/coq-community/run-coq-bug-minimizer/issues/2#issuecomment-2420152150
> Don't try to clobber glob files with ambiguous time stamps that fail to build

- coq_tools/find_bug.py
- coq_tools/import_util.py
- coq_tools/util.py
We add -R for user-contrib developments only in cases where coqc fails.
> Hack to work around lack of installed .glob

- examples/run-example-027.sh
Blindly edit for compat with https://github.com/coq/coq/pull/19599#issuecomment-2422221331
> Hopeful compatibility with coq/coq#19599

- coq_tools/coq_running_support.py
This will make things a bit more robust to missing coqlib
> Use -nois and -boot for modname validity checking

- coq_tools/coq_running_support.py
- coq_tools/coq_version.py
This should take care of the meat of #242.
> Thread coqlib through coq running support

- coq_tools/coq_running_support.py
- coq_tools/coq_version.py
Hopefully this will make the process more robust to missing coqlib.
> Use -boot -nois in more places

- coq_tools/absolutize_imports.py
- coq_tools/coq_version.py
- coq_tools/diagnose_error.py
- coq_tools/find_bug.py
- coq_tools/get_admitted_names.py
- coq_tools/import_util.py
- coq_tools/inline_imports.py
- coq_tools/minimize_requires.py
- coq_tools/replace_imports.py
- coq_tools/split_definitions.py
- coq_tools/split_definitions_old.py
- coq_tools/split_file.py
We can now pass `--coqc` multiple times, allowing for multiple word commands.
Unfortunately no tests for this at the moment.
> Add support for `rocq c`

- coq_tools/diagnose_error.py
- coq_tools/find_bug.py
> Wire up --ocamlpath

- coq_tools/find_bug.py
- coq_tools/split_definitions.py
- examples/Makefile
- examples/example_067/example_067.v
- examples/run-example-067.sh
> Add `--add-proof-using`

- coq_tools/coq_running_support.py
- coq_tools/find_bug.py
- coq_tools/replace_imports.py
> Use `Print Options` for better minimization control

- coq_tools/find_bug.py
This will make debugging easier
Variations are written under the same basic temporary name, with a variety of intermediate extensions
> When inlining fails, write all variations

- coq_tools/find_bug.py
- examples/example_068/example_068.v
- examples/run-example-068.sh
Thanks to @siraben for catching this
> Also admit lemmas that end with Admitted

- coq_tools/split_definitions.py
> Record outputs of coqc/coqtop in statements

- coq_tools/find_bug.py
> Add a pass to move both Requires and Declare Custom Entrys to the top

- coq_tools/split_definitions.py
> Add split_statements_to_definitions_with_options

- coq_tools/find_bug.py
This pass should not really be failing much
> log intermediates when require lifting fails

- coq_tools/import_util.py
- coq_tools/memoize.py
Also be more efficient in comparing libs by using @cache
> Fix the problem where d1' < d2' and d2' < d1' can be true in compare_libs
